#ifndef PLANETIO_ENGINECONSTANTS_H
#define PLANETIO_ENGINECONSTANTS_H

#define NB_BODIES 128
#define NB_PLAYERS 10

#define G_CONSTANT 	1.0634E4
#define MIN_NONNULL 	1.00E-20

#define UNIVERSE_SIZE 2000.0


#endif //PLANETIO_ENGINECONSTANTS_H
