#ifndef PLANETIO_STELLARCONSTANTS_H
#define PLANETIO_STELLARCONSTANTS_H

#define SUN_MASS 	1.9891E5
#define EARTH_MASS 	5.9736E3
#define MOON_MASS 	7.3477
#define D_SUN_EARTH 500.0
#define EARTH_SPEED	1.0

#endif //PLANETIO_STELLARCONSTANTS_H
